version: "3.7"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mysqldata:
  pgdata:
